CREATE TABLE IF NOT EXISTS users (
    id BIGINT PRIMARY KEY,
    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS banks (
    id BIGINT PRIMARY KEY,
    name VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS cards (
    id BIGINT PRIMARY KEY,
    userid BIGINT NOT NULL,
    bankid BIGINT NOT NULL,
    FOREIGN KEY (userid) REFERENCES users(id) ON UPDATE NO ACTION ON DELETE NO ACTION,
    FOREIGN KEY (bankid) REFERENCES banks(id) ON UPDATE NO ACTION ON DELETE NO ACTION,
    name VARCHAR(50) NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE
);
