// Code generated by MockGen. DO NOT EDIT.
// Source: ./rabbitmq.go

// Package mock is a generated GoMock package.
package mock

import (
	models "card-project/models"
	rabbitmq "card-project/repositories/rabbitmq"
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	pgconn "github.com/jackc/pgx/v5/pgconn"
)

// MockuserRepo is a mock of userRepo interface.
type MockuserRepo struct {
	ctrl     *gomock.Controller
	recorder *MockuserRepoMockRecorder
}

// MockuserRepoMockRecorder is the mock recorder for MockuserRepo.
type MockuserRepoMockRecorder struct {
	mock *MockuserRepo
}

// NewMockuserRepo creates a new mock instance.
func NewMockuserRepo(ctrl *gomock.Controller) *MockuserRepo {
	mock := &MockuserRepo{ctrl: ctrl}
	mock.recorder = &MockuserRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockuserRepo) EXPECT() *MockuserRepoMockRecorder {
	return m.recorder
}

// DeleteUserID mocks base method.
func (m *MockuserRepo) DeleteUserID(ctx context.Context, id int) (pgconn.CommandTag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUserID", ctx, id)
	ret0, _ := ret[0].(pgconn.CommandTag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteUserID indicates an expected call of DeleteUserID.
func (mr *MockuserRepoMockRecorder) DeleteUserID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUserID", reflect.TypeOf((*MockuserRepo)(nil).DeleteUserID), ctx, id)
}

// PostUser mocks base method.
func (m *MockuserRepo) PostUser(ctx context.Context, userData models.NewUser) (models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PostUser", ctx, userData)
	ret0, _ := ret[0].(models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PostUser indicates an expected call of PostUser.
func (mr *MockuserRepoMockRecorder) PostUser(ctx, userData interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PostUser", reflect.TypeOf((*MockuserRepo)(nil).PostUser), ctx, userData)
}

// MockRabbitMQ is a mock of RabbitMQ interface.
type MockRabbitMQ struct {
	ctrl     *gomock.Controller
	recorder *MockRabbitMQMockRecorder
}

// MockRabbitMQMockRecorder is the mock recorder for MockRabbitMQ.
type MockRabbitMQMockRecorder struct {
	mock *MockRabbitMQ
}

// NewMockRabbitMQ creates a new mock instance.
func NewMockRabbitMQ(ctrl *gomock.Controller) *MockRabbitMQ {
	mock := &MockRabbitMQ{ctrl: ctrl}
	mock.recorder = &MockRabbitMQMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRabbitMQ) EXPECT() *MockRabbitMQMockRecorder {
	return m.recorder
}

// NewConn mocks base method.
func (m *MockRabbitMQ) NewConn(userRepo MockuserRepo) rabbitmq.RabbitMQ {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewConn", userRepo)
	ret0, _ := ret[0].(rabbitmq.RabbitMQ)
	return ret0
}

// NewConn indicates an expected call of NewConn.
func (mr *MockRabbitMQMockRecorder) NewConn(userRepo interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewConn", reflect.TypeOf((*MockRabbitMQ)(nil).NewConn), userRepo)
}

// NewConsumer mocks base method.
func (m *MockRabbitMQ) NewConsumer(ctx context.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "NewConsumer", ctx)
}

// NewConsumer indicates an expected call of NewConsumer.
func (mr *MockRabbitMQMockRecorder) NewConsumer(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewConsumer", reflect.TypeOf((*MockRabbitMQ)(nil).NewConsumer), ctx)
}

// ProduceDeleteCard mocks base method.
func (m *MockRabbitMQ) ProduceDeleteCard(ctx context.Context, id int) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ProduceDeleteCard", ctx, id)
}

// ProduceDeleteCard indicates an expected call of ProduceDeleteCard.
func (mr *MockRabbitMQMockRecorder) ProduceDeleteCard(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProduceDeleteCard", reflect.TypeOf((*MockRabbitMQ)(nil).ProduceDeleteCard), ctx, id)
}

// ProduceDeleteUser mocks base method.
func (m *MockRabbitMQ) ProduceDeleteUser(ctx context.Context, id int) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ProduceDeleteUser", ctx, id)
}

// ProduceDeleteUser indicates an expected call of ProduceDeleteUser.
func (mr *MockRabbitMQMockRecorder) ProduceDeleteUser(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProduceDeleteUser", reflect.TypeOf((*MockRabbitMQ)(nil).ProduceDeleteUser), ctx, id)
}

// ProducePostCard mocks base method.
func (m *MockRabbitMQ) ProducePostCard(ctx context.Context, userData models.NewCard) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ProducePostCard", ctx, userData)
}

// ProducePostCard indicates an expected call of ProducePostCard.
func (mr *MockRabbitMQMockRecorder) ProducePostCard(ctx, userData interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProducePostCard", reflect.TypeOf((*MockRabbitMQ)(nil).ProducePostCard), ctx, userData)
}

// ProducePostUser mocks base method.
func (m *MockRabbitMQ) ProducePostUser(ctx context.Context, userData models.NewUser) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ProducePostUser", ctx, userData)
}

// ProducePostUser indicates an expected call of ProducePostUser.
func (mr *MockRabbitMQMockRecorder) ProducePostUser(ctx, userData interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProducePostUser", reflect.TypeOf((*MockRabbitMQ)(nil).ProducePostUser), ctx, userData)
}
